### PR TITLE
Allow viewing of photosphere depending on exif data: UsePanoramaViewer

### PR DESCRIPTION
**Pull request by shemgp**
So you don't need to set the photo as photosphere.

### CODE REVIEW

**Comment by mistic100** [comment]
What happens if exiftool is not available ?

It is probably no a good idea to systematically read exif data, this will kill big galleries.
It should be done once at upload time.

@plegall can correct me on this.

**Comment by plegall** [comment]
If you only do it on picture.php for a single photo, I would say it's OK to execute exiftool (if available of course). If you need to find "all photosphere" or if you need the information on the page of the photo, you can't execute exiftool on all photos, you need a cache in the database.

**Comment by shemgp** [comment]
@mistic100 If `exiftool` doesn't exist it'll return a blank json, so it won't enter the if statement and not set it as is_sphere.

@plegall Grepping `render_element_content` in Piwigo source and it seems that it's only called in `picture.php`.  

I've added code to set `is_sphere` also using after photo is uploaded.

I modified my previous code a little bit, so that it won't run exiftool everytime. I didn't remove it so that my previously upload sphere files will still show a sphere even if is_sphere is not set.

**Comment by mistic100** [comment]
You are still doing it everytime for every non-photosphere picture. I don't want that.

Also I don't think "format_exif_data" is the right event for processing uploaded files, I don't remember all events but there certainly is a better solution.

**Pull request closed without merging**
